### ISSUE TITLE
Strings Rewrite

### ISSUE THREAD

**Issue by ddworken** [redox-os/binutils#1]
No idea if you are interested, but when I was first getting started with Rust I wrote [my own implementation of strings in rust](https://github.com/ddworken/RStrings). It already has support for Unicode, multiple threads, and a number of other helpful options (along with all of the other options that strings offers by default). 

If you are interested I would be more than happy to re-license it as MIT so it can be merged. 

I'll admit the code quality isn't great (if we're merging it I'll spend some time cleaning it up!) but it will save you some work with adding all the extra features.

**Comment by Ticki** [comment]
Seems pretty promising. Will read through it.

**Comment by Ticki** [comment]
I have some criticism for it.

- It is quite slow, since you're doing many unnecessary allocation.
- It needs some extensive cleanup.
- **It does not print printable UTF8 chars, it prints valid one.**
- For such a lightweigt utility, there is no need for multithreading. The overhead from locks, sync, syscalls, and so on, is higher than the gain.
- `print!()` is evil. It construct a new `Stdout` _every single time_.
- It generates lots of warnings (code should be warning free!)
- Where is the exit codes?
- Nested indentation is the root of all evil. No reason for more than 5 levels of indentation.

**Comment by ddworken** [comment]
Thanks for the feedback! I think I'll just submit a few PRs adding a few of the features to yours.

**Comment by Ticki** [comment]
Sure thing.
